### ISSUE TITLE
Maven javadoc plugin doesn't work on WSL

### ISSUE THREAD

**Issue by tnevolin** [lightstep/otel-launcher-java#118]
I am building this project on WSL.

When I run `make build` I get this error:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.2.0:jar (attach-javadoc) on project opentelemetry-common: MavenReportException: Error while generating Javadoc: Unable to find javadoc command: The environment variable JAVA_HOME is not correctly set. -> [Help 1]
```

I have checked my variables. `JAVA_HOME` is set in `.profile` so it is available to all programs. `javadoc` is also directly accessible from `/usr/bin`.

Internet search suggests this is a bug in Maven javadoc plugin. I have updated javadoc plugin to latest version (3.3.1) and build passes.

Please update javadoc plugin to latest version as above.

**Comment by carlosalberto** [comment]
Closed via #119
