### ISSUE TITLE
Update CircleCI notifications

### ISSUE THREAD

**Issue by carlosalberto** [lightstep/otel-launcher-java#5]
See https://app.circleci.com/pipelines/github/lightstep/otel-launcher-java/22/workflows/c084e9e3-cdf5-4204-bceb-08038122be09 - it shows we are still running well after renaming this repo, *yet* I can't see any status indicator anywhere. Would you mind digging into this @malafeev ?

**Comment by malafeev** [comment]
@carlosalberto looks fine, I added circleci badge to readme in #6

**Comment by carlosalberto** [comment]
Closed via #6
