### ISSUE TITLE
Update the 0.9.0 Release with CHANGELOG info

### ISSUE THREAD

**Issue by carlosalberto** [lightstep/otel-launcher-java#56]
We need to update the CHANGELOG and also include such information in the tag itself (https://github.com/lightstep/otel-launcher-java/releases/tag/0.9.0).

It also would be nice to mention what are the improvements (rather than changes), i.e. no more OTLP metrics error messages.

**Comment by malafeev** [comment]
PR: https://github.com/lightstep/otel-launcher-java/pull/55
