### ISSUE TITLE
`lightstep-opentelemetry-javaagent-0.14.0.jar` reports errors when doing instrument

### ISSUE THREAD

**Issue by yaojingguo** [lightstep/otel-launcher-java#88]
**Describe the bug**
`lightstep-opentelemetry-javaagent-0.14.0.jar` reports errors when doing instrument. But `lightstep-opentelemetry-javaagent-0.8.0.jar` reports no error.

**To Reproduce**
```
$ cd examples/agent
$ make build
$ make run
```

**Expected behavior**
No errors should be reported.

**Comment by malafeev** [comment]
I guess it is due to unreleased changes. 
@yaojingguo please try again with just released 0.16.0

**Comment by yaojingguo** [comment]
Yes, 0.16.0 works.
